### ISSUE TITLE
Test for T300 (xbone Version) 

### ISSUE THREAD

**Issue by MaestroGlanz** [scarburato/t150_driver#17]
I read somewhere, that you are looking for testers. I want to test it for a Thrustmaster T300 wheel with ETS2 on steam. What do I have to change? Do I have to change anything?

**Comment by scarburato** [comment]
Take a look here https://github.com/Kimplul/hid-tmff2

**Comment by MaestroGlanz** [comment]
Thanks. Is there a possibility to unify the drivers? I mean, they should not deviate too much, as they are from the same company.
