### ISSUE TITLE
ETS2 FFB

### ISSUE THREAD

**Issue by Totten98** [scarburato/t150_driver#22]
Hello,
It's been a while now since i'm trying to get this working. Everything works fine in ets2 except for the most important thing:
The auto centering with the ffb while the truck is moving. i can't get this to work. everything else of the ffb works fine.
I don't know if it's a problem on my side or if it doesn't work at all.
I could play with the "enable_autocenter" on but i don't really like it.
Can you help me in some way?

Thanks you for all the job you did! Totten

**Comment by Totten98** [comment]
Solved by using `hid` branch.

**Comment by vayerx** [comment]
Auto-centering in `master` works for me with the following setup:
`ATTR{range}="1080", ATTR{gain}="20", ATTR{autocenter}="30", ATTR{enable_autocenter}="y"`
Increasing of `gain` and `autocenter` gives better centering. For decent centering I'd recommend using 50+. Auto-centering doesn't work at all with lower values of `gain` or `autocenter`. `range` doesn't matter — included it just in case.
