### ISSUE TITLE
hid_tminit was integrated on kernel since 5.13

### ISSUE THREAD

**Issue by albfan** [scarburato/t150_driver#35]
https://patchwork.kernel.org/project/linux-input/patch/20210131090045.10636-1-dario.pagani.146@gmail.com/#24038275

https://elixir.bootlin.com/linux/v5.13/source/drivers/hid/hid-thrustmaster.c

Probably worth to mention on README.md

Can I provide a patch?

**Comment by scarburato** [comment]
sure

**Comment by albfan** [comment]
check #36

**Comment by albfan** [comment]
Thanks!
