### ISSUE TITLE
Implement switch for combined pedals

### ISSUE THREAD

**Issue by albfan** [scarburato/t150_driver#41]
Based on #40 probably combined pedals are set using command

0x42 05

Do we have any documentation for thrustmaster codes?

**Comment by albfan** [comment]
I will implement a PR to test but confirm and see other addresses will make this easier

**Comment by Kimplul** [comment]
> Do we have any documentation for thrustmaster codes?

Afraid not really, they seem to be exclusive to each wheel and not public information. Only known bits are what's been reverse engineered.

**Comment by albfan** [comment]
Ok, have to do some test (like if setup is stored in device so windows driver reads it from config or similar) after that reserch (when I found how it works) we can think on how to implement it

**Comment by albfan** [comment]
Seems this `0x42` codes are already documented but didn't change anything:

https://github.com/scarburato/t150_driver/blob/fdb83ef67aa544da92d81ab81a5fe45371168a16/hid-t150/settings.h#L15-L20

**Comment by albfan** [comment]
So after debug with wireshark, hid report doesn't change (each pedal send same bytes), so this seems to be a software implementation, that redirects the report.

It can be reopen if someone miss this feature, but probably game or game manager (like steam) should deal with this
