### ISSUE TITLE
90° Deadzone in both directions of wheel

### ISSUE THREAD

**Issue by toscdesign** [scarburato/t150_driver#45]
I found that wverything is working so far with your driver.
Only the wheel it self has the issue of an 90° deadzone in both directions.

Is there any function in your driver to set it to 0° ?

**Comment by albfan** [comment]
t150 only report wheel position, probably deadzone is a configuration for your app consuming wheel input

https://steamcommunity.com/app/493490/discussions/0/1318836262656446804/?l=czech

We can reopen if you provide more info about how you detect the deadzone
