### ISSUE TITLE
First 90 degrees not reported

### ISSUE THREAD

**Issue by Xnoahg** [scarburato/t150_driver#47]
the first 45 degrees left and 45 degrees right are not reported by the wheel

Wheel: Thrustmaster T150
Distro: Arch Linux

**Comment by Xnoahg** [comment]
i noticed some other people also have the same issue, however I've tried all the provided solutions to no avail.

Im going to try a few other things as well, if i figure out whats causing it and/or the fix ill post that here

**Comment by albfan** [comment]
Probably a deadzone configured by your game. Check #45
