### ISSUE TITLE
The install.sh script breaks linux-headers directories somehow

### ISSUE THREAD

**Issue by CyntexMore** [scarburato/t150_driver#57]
When you run the `install.sh` script some `linux-headers` directories get removed somehow. Had to reinstall `linux-headers` with `sudo pacman -S linux-headers` manually. Not just for me because I asked someone to try it too. After doing this once I can complete the installation without any issues.

**Comment by albfan** [comment]
Without more info looks like you upgrade your kernel and miss some linux headers to rebuild the module

We can reopen if you give more details on what is removed and what needs to be reinstalled
